import React, { useEffect, useMemo, useState } from 'react';
import { Database, FileSpreadsheet, Key, Link2, RefreshCw, Search, UploadCloud, X } from 'lucide-react';
import { DatasetsOverview } from '../types';
import { getDatasetsOverview, getTablePreview, uploadDataset } from '../api/client';

export const DatasetsPageV2: React.FC = () => {
  const [overview, setOverview] = useState<DatasetsOverview | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [preview, setPreview] = useState<any>(null);
  const [search, setSearch] = useState('');
  const [busy, setBusy] = useState(false);
  const [previewBusy, setPreviewBusy] = useState(false);
  const load = async () => { setBusy(true); try { setOverview(await getDatasetsOverview()); } finally { setBusy(false); } };
  useEffect(() => { load(); }, []);
  const inspect = async (name: string) => { setSelected(name); setPreviewBusy(true); try { setPreview(await getTablePreview(name)); } finally { setPreviewBusy(false); } };
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const files = event.target.files; if (!files?.length) return; setBusy(true); try { for (const file of Array.from(files)) await uploadDataset(file); await load(); } catch (err: any) { alert(err.message); } finally { setBusy(false); event.target.value = ''; } };
  const filtered = preview?.records?.filter((row: any) => Object.values(row).some(value => String(value ?? '').toLowerCase().includes(search.toLowerCase()))) || [];
  const graph = useMemo(() => { if (!overview) return []; const names = overview.datasets.map(d => d.dataset_name); return names.map((name, index) => ({ name, x: 10 + (index % 4) * 25, y: 12 + Math.floor(index / 4) * 38 })); }, [overview]);
  if (!overview) return <div className="flex min-h-[60vh] items-center justify-center text-sm text-slate-400"><RefreshCw className="mr-2 h-4 w-4 animate-spin" /> Profiling datasets…</div>;
  return <div className="space-y-6">
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-blue-600"><Database className="h-4 w-4" /> Data foundation</div><h1 className="mt-2 text-2xl font-bold text-slate-900 dark:text-white">Profile the data before you trust the answer.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Inspect quality, keys, schemas and inferred relationships across every ingested dataset.</p></div><div className="flex items-center gap-2"><span className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Overall quality {overview.overall_quality_score.toFixed(1)}%</span><label className="inline-flex cursor-pointer items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white"><UploadCloud className="h-4 w-4" /> {busy ? 'Processing…' : 'Upload CSV / XLSX'}<input type="file" multiple accept=".csv,.xlsx,.xls" onChange={upload} className="hidden" /></label></div></div></section>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{overview.datasets.map(ds => <article key={ds.dataset_name} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div><h2 className="text-sm font-bold text-slate-900 dark:text-white">{ds.dataset_name}</h2><p className="mt-1 text-[10px] font-mono text-slate-400">{ds.file_name}</p></div><span className={`rounded-md px-2 py-1 text-[10px] font-bold ${ds.data_quality_score >= 90 ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{ds.data_quality_score.toFixed(1)}% quality</span></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-950"><div className="text-[10px] uppercase text-slate-400">Rows</div><div className="mt-1 font-mono text-sm font-bold">{ds.row_count.toLocaleString('en-IN')}</div></div><div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-950"><div className="text-[10px] uppercase text-slate-400">Columns</div><div className="mt-1 font-mono text-sm font-bold">{ds.column_count}</div></div></div><div className="mt-4"><div className="mb-2 flex items-center gap-1 text-[10px] font-bold uppercase text-slate-400"><Key className="h-3 w-3" /> Candidate keys</div><div className="flex flex-wrap gap-1">{ds.likely_primary_keys.map(key => <span key={key} className="rounded bg-amber-50 px-2 py-1 font-mono text-[10px] text-amber-700">{key}</span>)}{!ds.likely_primary_keys.length && <span className="text-[10px] text-slate-400">No obvious unique key</span>}</div></div><div className="mt-4 flex flex-wrap gap-1">{ds.columns.slice(0, 7).map(col => <span key={col.name} className="rounded bg-slate-100 px-1.5 py-1 font-mono text-[9px] text-slate-500 dark:bg-slate-800">{col.name}</span>)}</div><button onClick={() => inspect(ds.dataset_name)} className="mt-4 w-full rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-200">Inspect sample records</button></article>)}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-sm font-bold text-slate-900 dark:text-white"><Link2 className="h-4 w-4 text-blue-500" /> Schema relationship graph</h2><p className="mt-1 text-xs text-slate-500">Heuristic FK matching across observed value domains.</p></div><span className="text-[10px] font-bold text-slate-400">{overview.relationships.length} links</span></div><div className="relative mt-5 min-h-[260px] overflow-hidden rounded-xl border border-slate-100 bg-slate-50 dark:border-slate-800 dark:bg-slate-950"><svg className="absolute inset-0 h-full w-full">{overview.relationships.map((rel, i) => { const a = graph.find(n => n.name === rel.source_dataset); const b = graph.find(n => n.name === rel.target_dataset); if (!a || !b) return null; return <line key={i} x1={`${a.x}%`} y1={`${a.y}%`} x2={`${b.x}%`} y2={`${b.y}%`} stroke="currentColor" strokeWidth="1.5" className="text-blue-300 dark:text-blue-900" />; })}</svg>{graph.map(node => <div key={node.name} className="absolute w-36 -translate-x-1/2 -translate-y-1/2 rounded-xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-700 dark:bg-slate-900" style={{ left: `${node.x}%`, top: `${node.y}%` }}><div className="text-xs font-bold text-slate-800 dark:text-slate-100">{node.name}</div><div className="mt-1 text-[9px] text-slate-400">{overview.datasets.find(d => d.dataset_name === node.name)?.row_count.toLocaleString('en-IN')} rows</div></div>)}</div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 dark:bg-slate-950"><tr>{['Source','Column','Target','Column','Type','Match','Confidence'].map(h => <th key={h} className="px-3 py-2 font-semibold text-slate-500">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{overview.relationships.map((r, i) => <tr key={i}><td className="px-3 py-2 font-semibold">{r.source_dataset}</td><td className="px-3 py-2 font-mono text-blue-600">{r.source_column}</td><td className="px-3 py-2 font-semibold">{r.target_dataset}</td><td className="px-3 py-2 font-mono text-amber-600">{r.target_column}</td><td className="px-3 py-2">{r.relationship_type}</td><td className="px-3 py-2">{r.match_rate_pct}%</td><td className="px-3 py-2">{r.confidence}</td></tr>)}</tbody></table></div></section>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4"><div className="flex max-h-[85vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-200 p-4 dark:border-slate-800"><div><div className="flex items-center gap-2 text-sm font-bold"><FileSpreadsheet className="h-4 w-4 text-blue-500" /> {selected}</div><div className="text-[10px] text-slate-400">First 100 records</div></div><div className="flex items-center gap-2"><div className="relative"><Search className="absolute left-2 top-2 h-3.5 w-3.5 text-slate-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search records" className="w-52 rounded-lg border border-slate-200 py-1.5 pl-7 pr-2 text-xs outline-none dark:border-slate-700 dark:bg-slate-950" /></div><button onClick={() => { setSelected(null); setPreview(null); setSearch(''); }}><X className="h-5 w-5 text-slate-400" /></button></div></div><div className="overflow-auto p-4">{previewBusy ? <div className="py-16 text-center text-sm text-slate-400">Loading preview…</div> : <table className="min-w-full text-left text-[10px]"><thead className="sticky top-0 bg-slate-100 dark:bg-slate-800"><tr>{preview?.columns?.map((col: string) => <th key={col} className="whitespace-nowrap px-3 py-2 font-bold">{col}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{filtered.map((row: any, i: number) => <tr key={i}>{preview.columns.map((col: string) => <td key={col} className="whitespace-nowrap px-3 py-2 font-mono text-slate-500">{String(row[col] ?? '')}</td>)}</tr>)}</tbody></table>}</div></div></div>}
  </div>;
};
