import React, { useEffect, useMemo, useState } from 'react';
import { Download, FileText, Printer, ShieldCheck } from 'lucide-react';
import { ConsultingDashboard } from '../types';
import { getDownloadPdfUrl, getReportContent } from '../api/client';

interface Props { dashboardData: ConsultingDashboard; }
const inr = (value: number) => { const abs = Math.abs(value); const sign = value < 0 ? '-' : ''; if (abs >= 10_000_000) return `${sign}₹${(abs / 10_000_000).toFixed(2)}Cr`; if (abs >= 100_000) return `${sign}₹${(abs / 100_000).toFixed(2)}L`; return `${sign}₹${Math.round(abs).toLocaleString('en-IN')}`; };

export const ReportsPage: React.FC<Props> = ({ dashboardData }) => {
  const [report, setReport] = useState<any>(null);
  useEffect(() => { getReportContent().then(setReport).catch(() => setReport(null)); }, []);
  const k = dashboardData.kpi_summary;
  const costs = report?.costs || {};
  const root = dashboardData.driver_tree;
  const totalCostDelta = useMemo(() => Object.values(costs).reduce((sum: number, value: any) => sum + Number(value?.delta || 0), 0), [costs]);
  const Section = ({ n, title, children }: { n: number; title: string; children: React.ReactNode }) => <section className="space-y-3"><h2 className="border-l-4 border-blue-600 pl-3 text-sm font-bold uppercase tracking-wider text-slate-900 dark:text-white">{n}. {title}</h2>{children}</section>;
  return <div className="space-y-6">
    <div className="no-print flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between dark:border-slate-800 dark:bg-slate-900"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-blue-600"><FileText className="h-4 w-4" /> Executive deliverable</div><h1 className="mt-1 text-lg font-bold text-slate-900 dark:text-white">10-section decision intelligence report</h1><p className="mt-1 text-xs text-slate-500">Generated from the same deterministic snapshot powering the application.</p></div><div className="flex gap-2"><button onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-700"><Printer className="h-3.5 w-3.5" /> Print</button><button onClick={() => window.open(getDownloadPdfUrl(), '_blank')} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white"><Download className="h-3.5 w-3.5" /> Official PDF</button></div></div>
    <article className="mx-auto max-w-5xl space-y-10 rounded-2xl border border-slate-200 bg-white p-7 shadow-sm md:p-10 print:border-0 print:shadow-none dark:border-slate-800 dark:bg-slate-900">
      <header className="border-b-2 border-slate-900 pb-6 dark:border-white"><div className="text-[10px] font-bold uppercase tracking-[0.16em] text-blue-600">Consulting in a Box · Decision Intelligence</div><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-slate-900 dark:text-white">{dashboardData.company_name} Performance Diagnostic</h1><p className="mt-2 text-xs text-slate-500">{dashboardData.industry} · {dashboardData.quarter_evaluated} · INR</p></header>
      <Section n={1} title="Executive Summary"><div className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-slate-700 dark:border-blue-900/50 dark:bg-blue-950/20 dark:text-slate-200">Net operating profit changed <b>{k.net_profit_growth_pct.toFixed(1)}%</b> QoQ, from <b>{inr(k.net_profit_prior)}</b> to <b>{inr(k.net_profit_current)}</b>. Revenue changed {k.revenue_growth_pct.toFixed(1)}%, while net margin moved {k.net_margin_delta_pp.toFixed(1)} pp. The driver tree reconciles the observed profit variance into revenue and cost impacts.</div></Section>
      <Section n={2} title="Business Problem Definition"><p className="text-sm leading-6 text-slate-600 dark:text-slate-300"><b>Problem:</b> {dashboardData.problem_title}. The objective is to isolate material performance drivers, distinguish measured facts from hypotheses, and size actions using transparent sensitivity assumptions.</p></Section>
      <Section n={3} title="Strategic KPI Scorecard"><div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="min-w-full text-left text-xs"><thead className="bg-slate-950 text-white"><tr><th className="px-4 py-3">Metric</th><th className="px-4 py-3">Prior</th><th className="px-4 py-3">Current</th><th className="px-4 py-3">Change</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{[["Revenue", inr(k.revenue_prior), inr(k.revenue_current), `${k.revenue_growth_pct.toFixed(1)}%`],["Gross Profit", inr(k.gross_profit_prior), inr(k.gross_profit_current), `${k.gross_profit_growth_pct.toFixed(1)}%`],["Net Profit", inr(k.net_profit_prior), inr(k.net_profit_current), `${k.net_profit_growth_pct.toFixed(1)}%`],["Orders", k.orders_prior.toLocaleString('en-IN'), k.orders_current.toLocaleString('en-IN'), `${k.orders_growth_pct.toFixed(1)}%`],["AOV", inr(k.aov_prior), inr(k.aov_current), `${k.aov_growth_pct.toFixed(1)}%`],["CAC", inr(k.cac_prior), inr(k.cac_current), `${k.cac_growth_pct.toFixed(1)}%`],["Net Margin", `${k.net_margin_prior_pct.toFixed(1)}%`, `${k.net_margin_current_pct.toFixed(1)}%`, `${k.net_margin_delta_pp.toFixed(1)} pp`],["Churn", `${k.churn_rate_prior_pct.toFixed(1)}%`, `${k.churn_rate_current_pct.toFixed(1)}%`, `${k.churn_rate_delta_pp.toFixed(1)} pp`]].map(row => <tr key={row[0]}><td className="px-4 py-2.5 font-semibold text-slate-800 dark:text-slate-100">{row[0]}</td><td className="px-4 py-2.5 font-mono text-slate-500">{row[1]}</td><td className="px-4 py-2.5 font-mono text-slate-800 dark:text-slate-100">{row[2]}</td><td className="px-4 py-2.5 font-mono font-semibold text-slate-600">{row[3]}</td></tr>)}</tbody></table></div></Section>
      <Section n={4} title="Major Findings & Classification"><div className="space-y-2">{dashboardData.insights.map(item => <div key={item.id} className="rounded-xl border border-slate-200 p-3 text-xs dark:border-slate-800"><div className="font-bold text-slate-900 dark:text-white">[{item.classification}] {item.headline}</div><div className="mt-1 leading-5 text-slate-500">{item.narrative}</div><div className="mt-2 font-mono text-[10px] text-slate-400">Evidence: {item.evidence_id} · Confidence: {item.confidence}</div></div>)}</div></Section>
      <Section n={5} title="Root Cause Driver Tree"><div className="rounded-xl bg-slate-950 p-5 text-xs text-slate-200"><div className="font-bold text-white">{root.label}: {inr(root.prior_value)} → {inr(root.current_value)} ({root.delta_pct.toFixed(1)}%)</div>{root.children.map(child => <div key={child.id} className="mt-3 border-l border-slate-700 pl-4"><div className="font-semibold">{child.label} · {child.contribution_pct.toFixed(1)}% contribution</div><div className="mt-1 text-slate-400">Impact: {child.delta_value >= 0 ? '+' : ''}{inr(child.delta_value)}</div>{child.children.map(leaf => <div key={leaf.id} className="mt-1 pl-3 text-slate-400">↳ {leaf.label}: {leaf.contribution_pct.toFixed(1)}%</div>)}</div>)}</div></Section>
      <Section n={6} title="Supporting Evidence & Methodology"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-slate-200 p-4 text-xs dark:border-slate-800"><b>P&L bridge</b><p className="mt-1 text-slate-500">Revenue plus verified cost movements reconcile to current net profit.</p></div><div className="rounded-xl border border-slate-200 p-4 text-xs dark:border-slate-800"><b>Entity evidence</b><p className="mt-1 text-slate-500">Carrier, category and channel findings use relational aggregates.</p></div><div className="rounded-xl border border-slate-200 p-4 text-xs dark:border-slate-800"><b>Governance</b><p className="mt-1 text-slate-500">Material findings carry evidence IDs and executable SQL methodology.</p></div></div></Section>
      <Section n={7} title="Strategic Recommendations"><div className="space-y-3">{dashboardData.recommendations.map((rec, i) => <div key={rec.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-bold text-slate-900 dark:text-white">{String(i + 1).padStart(2, '0')}. {rec.title}</h3><span className="rounded-md bg-emerald-50 px-2 py-1 font-mono text-[10px] font-bold text-emerald-700">{rec.expected_impact_formatted}</span></div><p className="mt-2 text-xs leading-5 text-slate-600 dark:text-slate-300">{rec.recommendation}</p><p className="mt-2 text-xs leading-5 text-slate-500"><b>Why:</b> {rec.why}</p><div className="mt-3 text-[10px] font-mono text-slate-400">{rec.confidence} confidence · {rec.implementation_timeframe}</div></div>)}</div></Section>
      <Section n={8} title="What-If Scenario & Sensitivity Modeling"><p className="text-sm leading-6 text-slate-600 dark:text-slate-300">The Scenarios workspace applies explicit elasticity assumptions to price, marketing, churn, delivery cost, COGS and return-rate levers. Outputs are directional sensitivities, not forecasts. The interactive matrix evaluates price and delivery-cost combinations against the same verified base case.</p></Section>
      <Section n={9} title="Risks, Assumptions & Governance"><ul className="list-disc space-y-2 pl-5 text-sm leading-6 text-slate-600 dark:text-slate-300"><li>Observed relationships do not establish causality.</li><li>Scenario elasticity is an assumption and should be calibrated with experiments.</li><li>Source-system completeness and attribution quality can affect conclusions.</li><li>Recommendations should be validated against supplier capacity, service levels and controlled-test results.</li><li>Current modeled cost movement is {inr(totalCostDelta)} across the cost categories.</li></ul></Section>
      <Section n={10} title="Implementation Roadmap"><div className="grid gap-3 md:grid-cols-4">{[['0–30 days','Validate highest-impact cost and channel drivers.'],['30–60 days','Run controlled pricing, carrier and media allocation tests.'],['60–90 days','Measure realized contribution impact and refresh assumptions.'],['90+ days','Institutionalize recurring evidence-backed decision reviews.']].map(([phase,text]) => <div key={phase} className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><div className="text-xs font-bold text-blue-600">{phase}</div><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></div>)}</div></Section>
      <footer className="flex items-center gap-2 border-t border-slate-200 pt-4 text-[10px] text-slate-400 dark:border-slate-800"><ShieldCheck className="h-3.5 w-3.5 text-emerald-500" /> Generated from deterministic analytics · Monetary values are INR · AI interpretation is governed separately from numerical computation.</footer>
    </article>
  </div>;
};
