import React, { useEffect, useState } from 'react';
import { CheckCircle2, Grid3X3, RotateCcw, SlidersHorizontal, Sparkles, Target } from 'lucide-react';
import { ConsultingDashboard, ScenarioLevers, ScenarioResult } from '../types';
import { getSensitivityMatrix, simulateScenario } from '../api/client';

interface Props { data: ConsultingDashboard; }
const DEFAULT: ScenarioLevers = { price_change_pct: 0, marketing_spend_delta_pct: 0, churn_rate_delta_pp: 0, delivery_cost_delta_pct: 0, cogs_reduction_pct: 0, return_rate_delta_pp: 0 };
const meta: Array<{ key: keyof ScenarioLevers; label: string; min: number; max: number; step: number; suffix: string }> = [
  { key: 'price_change_pct', label: 'Price / AOV', min: -10, max: 20, step: 1, suffix: '%' },
  { key: 'marketing_spend_delta_pct', label: 'Marketing spend', min: -30, max: 20, step: 5, suffix: '%' },
  { key: 'churn_rate_delta_pp', label: 'Churn rate', min: -4, max: 3, step: .5, suffix: ' pp' },
  { key: 'delivery_cost_delta_pct', label: 'Delivery cost', min: -20, max: 15, step: 1, suffix: '%' },
  { key: 'cogs_reduction_pct', label: 'COGS reduction', min: -8, max: 8, step: 1, suffix: '%' },
  { key: 'return_rate_delta_pp', label: 'Return rate', min: -3, max: 3, step: .5, suffix: ' pp' },
];
const inr = (value: number) => { const abs = Math.abs(value); const sign = value < 0 ? '-' : ''; if (abs >= 10_000_000) return `${sign}₹${(abs / 10_000_000).toFixed(2)}Cr`; if (abs >= 100_000) return `${sign}₹${(abs / 100_000).toFixed(2)}L`; return `${sign}₹${Math.round(abs).toLocaleString('en-IN')}`; };

export const ScenariosPage: React.FC<Props> = ({ data }) => {
  const [levers, setLevers] = useState<ScenarioLevers>(DEFAULT);
  const [result, setResult] = useState<ScenarioResult | null>(null);
  const [matrix, setMatrix] = useState<any>(null);
  const [busy, setBusy] = useState(false);
  const [matrixBusy, setMatrixBusy] = useState(false);
  const run = async (next = levers) => { setBusy(true); try { setResult(await simulateScenario(next)); } finally { setBusy(false); } };
  useEffect(() => { run(DEFAULT); }, []);
  const set = (key: keyof ScenarioLevers, value: number) => setLevers(current => ({ ...current, [key]: value }));
  const recommended = () => { const next = { ...DEFAULT, price_change_pct: 5, delivery_cost_delta_pct: -8, churn_rate_delta_pp: -2 }; setLevers(next); run(next); };
  const loadMatrix = async () => { setMatrixBusy(true); try { setMatrix(await getSensitivityMatrix(levers)); } finally { setMatrixBusy(false); } };
  return <div className="space-y-6">
    <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-blue-600"><SlidersHorizontal className="h-4 w-4" /> Decision simulator</div><h1 className="mt-2 text-2xl font-bold text-slate-900 dark:text-white">Test decisions before you act.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Change six business levers and compare the modeled outcome against the verified current-period base case. These are sensitivity estimates, not forecasts.</p></div><div className="flex gap-2"><button onClick={() => { setLevers(DEFAULT); run(DEFAULT); }} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200"><RotateCcw className="h-3.5 w-3.5" /> Reset</button><button onClick={recommended} className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white"><Target className="h-3.5 w-3.5" /> Illustrative case</button></div></div></section>
    <div className="grid gap-6 lg:grid-cols-[380px_1fr]">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-5 flex items-center justify-between"><h2 className="text-sm font-bold text-slate-900 dark:text-white">Decision levers</h2><span className="text-[10px] text-slate-400">Explicit assumptions</span></div><div className="space-y-5">{meta.map(item => { const value = levers[item.key] as number; return <div key={item.key}><div className="mb-2 flex justify-between"><span className="text-xs font-semibold text-slate-700 dark:text-slate-200">{item.label}</span><span className="font-mono text-xs font-bold text-blue-600">{value > 0 ? '+' : ''}{value}{item.suffix}</span></div><input aria-label={item.label} type="range" min={item.min} max={item.max} step={item.step} value={value} onChange={e => set(item.key, Number(e.target.value))} className="w-full accent-blue-600" /><div className="mt-1 flex justify-between text-[10px] text-slate-400"><span>{item.min}{item.suffix}</span><span>{item.max}{item.suffix}</span></div></div>; })}</div><button onClick={() => run()} disabled={busy} className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-50">{busy ? 'Recalculating…' : 'Apply scenario'} <Sparkles className="h-3.5 w-3.5" /></button></section>
      <section className="space-y-6"><div className="rounded-2xl bg-slate-950 p-6 text-white"><div className="text-xs font-bold uppercase tracking-[0.14em] text-blue-400">Modeled outcome</div><p className="mt-3 text-sm leading-7 text-slate-200">{result?.executive_verdict || 'Adjust the levers and apply the scenario.'}</p></div>{result && <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-4"><h2 className="text-sm font-bold text-slate-900 dark:text-white">Baseline vs scenario</h2><p className="mt-1 text-xs text-slate-500">Metric-aware signals: higher profit is favorable; higher CAC/churn is unfavorable.</p></div><div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="min-w-full text-left text-xs"><thead className="bg-slate-50 dark:bg-slate-950"><tr><th className="px-4 py-3">Metric</th><th className="px-4 py-3">Base</th><th className="px-4 py-3">Scenario</th><th className="px-4 py-3">Delta</th><th className="px-4 py-3">Signal</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{Object.values(result.metrics).map(m => <tr key={m.metric_name}><td className="px-4 py-3 font-semibold text-slate-800 dark:text-slate-100">{m.metric_name}</td><td className="px-4 py-3 font-mono text-slate-500">{m.formatted_base}</td><td className="px-4 py-3 font-mono font-semibold">{m.formatted_scenario}</td><td className={`px-4 py-3 font-mono font-semibold ${m.is_positive_trend ? 'text-emerald-600' : 'text-rose-600'}`}>{m.formatted_delta}</td><td className="px-4 py-3">{m.is_positive_trend ? 'Favorable' : 'Unfavorable'}</td></tr>)}</tbody></table></div></div>}
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 text-sm font-bold text-slate-900 dark:text-white"><Grid3X3 className="h-4 w-4 text-blue-500" /> Price × delivery-cost sensitivity</h2><p className="mt-1 text-xs text-slate-500">A compact decision matrix around the selected baseline assumptions.</p></div><button onClick={loadMatrix} disabled={matrixBusy} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200">{matrixBusy ? 'Computing…' : 'Compute matrix'}</button></div>{matrix && <div className="mt-4 overflow-x-auto"><table className="min-w-full text-xs"><thead><tr><th className="p-2 text-left text-slate-400">Price ↓ / Delivery →</th>{matrix.delivery_cost_values.map((v: number) => <th key={v} className="p-2 font-mono">{v > 0 ? '+' : ''}{v}%</th>)}</tr></thead><tbody>{matrix.price_values.map((price: number, i: number) => <tr key={price} className="border-t border-slate-100 dark:border-slate-800"><td className="p-2 font-mono font-semibold">{price > 0 ? '+' : ''}{price}%</td>{matrix.cells[i].map((cell: any) => <td key={`${cell.price_change_pct}-${cell.delivery_cost_delta_pct}`} className={`p-2 text-center font-mono font-semibold ${cell.favorable ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{inr(cell.net_profit)}<span className="ml-1 text-[9px]">({cell.delta_pct > 0 ? '+' : ''}{cell.delta_pct.toFixed(1)}%)</span></td>)}</tr>)}</tbody></table></div>}</div>
      {result && <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="text-sm font-bold text-slate-900 dark:text-white">Model assumptions</h2><ul className="mt-3 grid gap-2 text-xs text-slate-500 md:grid-cols-2">{result.key_assumptions.map((item, i) => <li key={i} className="flex gap-2"><CheckCircle2 className="h-3.5 w-3.5 shrink-0 text-emerald-500" />{item}</li>)}</ul></div>}</section>
    </div>
  </div>;
};
